### ISSUE TITLE
Roadmap to `v2.0.0`

### ISSUE THREAD

**Issue by lumirlumir** [lumirlumir/npm-clang-format-node#111]
# Roadmap to `v2.0.0`

> [!CAUTION]
>
> The update is currently on hold due to cross-platform compatibility issues with clang-format 20.1.X, and we are waiting for a patch from LLVM.

The release of `clang-format` version 20 (`llvmorg-20.X.X`) coincides with the arrival of a major update.

With the release of `v2.0.0`, the following will be deprecated. (This lists will be updated regularly.)

## Deprecation Lists

- Support for `clang-format` version 19 (`llvmorg-19.X.X`) will be deprecated.

# TODO Lists

## :arrows_counterclockwise: Continuous Integrations

- [x] Update `llvm-build-bump-pr.yml` to support `llvmorg-21.X.X` [Release notes](https://releases.llvm.org/20.1.0/tools/clang/docs/ReleaseNotes.html)
    - [x] https://github.com/llvm/llvm-project/pull/124128
- [x] Add 'GitHub Actions Attestation Provenances' and 'npm build provenances' for a better security
    - [x] https://github.com/lumirlumir/npm-clang-format-node/pull/235
    - [x] https://github.com/lumirlumir/npm-clang-format-node/pull/250
    - [x] https://github.com/lumirlumir/npm-clang-format-node/pull/265

## :memo: Documentation

- [ ] Add 'GitHub Actions Attestation Provenances' and 'npm build provenances' related descriptions in `README.md` and `SECURITY.md`
- [x] Remove Maintainability badge from `README.md`: https://github.com/lumirlumir/npm-clang-format-node/pull/287
